import { build, type BuildOptions, type OutputFile, type Plugin as EsbuildPlugin } from "esbuild";
import { createHash } from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";

export interface PluginBundleResult {
  bytes: Uint8Array;
  sha256: string;
  /**
   * Versions of viewer-exposed packages this bundle was built against
   * (verbatim from `viewer-externals.json`). Recorded into the publish
   * manifest so the viewer's plugin loader can major-version-check on load.
   */
  externals: Record<string, string>;
  /** Final bundled byte size, for progress reporting. */
  byteSize: number;
}

export interface BundlePluginArgs {
  /**
   * Plugin entry — usually the plugin's compiled `dist/index.js` path so
   * we don't need a TypeScript toolchain inside the bundler.
   */
  entryPath: string;
  /**
   * Path to `viewer-externals.json`. Records the versions the bundle was
   * built against so the viewer can major-version-check at load time, even
   * though we currently bundle everything in.
   */
  viewerExternalsPath: string;
  /**
   * When true (default), `three`/`react`/etc. are bundled INTO the plugin
   * rather than left as bare-specifier externals. This makes the plugin
   * loadable from a blob URL in the viewer (which has no import map).
   *
   * Set false only if the host environment provides those modules via an
   * import map or globals — see the trade-off note in the implementation.
   */
  inlineExternals?: boolean;
}

interface ViewerExternalsFile {
  externals?: Record<string, string>;
}

function readViewerExternalsFile(viewerExternalsPath: string): Record<string, string> {
  if (!fs.existsSync(viewerExternalsPath)) {
    return {};
  }
  const raw = fs.readFileSync(viewerExternalsPath, "utf8");
  const parsed = JSON.parse(raw) as ViewerExternalsFile;
  return parsed.externals ?? {};
}

type ThreeExportsMap = Record<string, string[]>;

/**
 * Loads the cached list of three submodule exports from
 * `viewer-externals-three.json` at the repo root. Run
 * `node -e "..." ` to regenerate. Maps each module specifier (`three`,
 * `three/tsl`, `three/webgpu`) to its list of named exports.
 *
 * The virtual-three plugin uses these names to expose static named exports
 * that delegate to the host viewer's three instance via globalThis.
 */
function loadThreeExportsMap(repoRoot: string): ThreeExportsMap | null {
  const filePath = path.join(repoRoot, "viewer-externals-three.json");
  if (!fs.existsSync(filePath)) return null;
  try {
    const parsed = JSON.parse(fs.readFileSync(filePath, "utf8")) as Record<string, unknown>;
    const out: ThreeExportsMap = {};
    for (const [moduleName, value] of Object.entries(parsed)) {
      if (Array.isArray(value) && value.every((entry) => typeof entry === "string")) {
        out[moduleName] = value as string[];
      }
    }
    // Sanity: must include at least `three`.
    return out.three ? out : null;
  } catch {
    return null;
  }
}

/**
 * Builds an esbuild plugin that intercepts plugin imports of `three`,
 * `three/tsl`, and `three/webgpu` and replaces them with tiny virtual
 * modules that read the host viewer's instances from
 * `globalThis.__simularca_shared__[<modulePath>]`.
 *
 * Why: with each plugin shipping its own three copy, `instanceof THREE.Object3D`
 * fails because the plugin's THREE.Object3D is a different constructor
 * identity than the host's. Beam emitters / cross-sections silently fail
 * in the viewer ("must reference valid curve and primitive/mesh actors").
 *
 * The virtual module uses static destructuring against a known list of each
 * submodule's exports so named imports work without runtime fallback.
 */
function buildVirtualThreePlugin(exportsMap: ThreeExportsMap): EsbuildPlugin {
  const moduleNames = Object.keys(exportsMap);
  // Build a regex that matches any of the shared module paths exactly.
  // `three`, `three/tsl`, `three/webgpu`, etc.
  const filter = new RegExp(
    `^(${moduleNames.map((name) => name.replace(/[.+?^${}()|[\]\\]/g, "\\$&")).join("|")})$`
  );
  return {
    name: "simularca-virtual-three",
    setup(build) {
      build.onResolve({ filter }, (args) => ({
        path: args.path,
        namespace: "virtual-three"
      }));
      build.onLoad({ filter: /.*/, namespace: "virtual-three" }, (args) => {
        const moduleName = args.path;
        const names = exportsMap[moduleName] ?? [];
        const destructured = names.join(",\n  ");
        const contents = [
          `// Generated by simularca pluginBundler — host-shared "${moduleName}".`,
          `const __M__ = (globalThis).__simularca_shared__ && (globalThis).__simularca_shared__[${JSON.stringify(moduleName)}];`,
          `if (!__M__) throw new Error("Host viewer did not expose ${moduleName} on globalThis.__simularca_shared__. Bundle must run inside the Simularca viewer.");`,
          names.length > 0 ? `export const {\n  ${destructured}\n} = __M__;` : "",
          "export default __M__;"
        ]
          .filter(Boolean)
          .join("\n");
        return { contents, loader: "js" };
      });
    }
  };
}

/**
 * Bundles a non-core plugin into a single ES module suitable for the viewer
 * to dynamic-import via a blob URL.
 *
 * By default, externals like `three`/`react` are INLINED into the plugin so
 * the blob URL loads without needing an import map. Trade-off: each plugin
 * ships its own copy of three (~600 kB), and plugin-created `THREE.Mesh`
 * instances are a different constructor identity than the host's. Three.js
 * is mostly duck-typed at render time so this works for scene-additive
 * plugins; if a plugin relies on `instanceof THREE.X` against host objects,
 * it will fail and want `inlineExternals: false`.
 */
export async function bundlePlugin(args: BundlePluginArgs): Promise<PluginBundleResult> {
  if (!fs.existsSync(args.entryPath)) {
    throw new Error(`Plugin entry not found: ${args.entryPath}`);
  }
  const externals = readViewerExternalsFile(args.viewerExternalsPath);
  // We no longer inline three.js — the host viewer exposes its own three on
  // globalThis.__simularca_shared__.three and an esbuild plugin redirects
  // each plugin's `import * as THREE from "three"` to read from there.
  // Sharing the host's three is required for `instanceof THREE.Object3D`
  // (and similar) checks in plugins to succeed against host-created objects.
  const inlineExternals = args.inlineExternals ?? false;

  // Resolve the repo root from viewerExternalsPath (it sits next to
  // viewer-externals.json in the repo root).
  const repoRoot = path.dirname(args.viewerExternalsPath);
  const threeExportsMap = loadThreeExportsMap(repoRoot);
  const esbuildPlugins: EsbuildPlugin[] = [];
  if (!inlineExternals && threeExportsMap) {
    esbuildPlugins.push(buildVirtualThreePlugin(threeExportsMap));
  }
  // Only three submodules get the virtual-three treatment (shared with the
  // host viewer). Everything else — react, zustand, immer, etc. — must be
  // bundled INTO the plugin (the viewer has no import map for them), so we
  // leave them off the externals list. The browser would otherwise fail
  // with "Failed to resolve module specifier" on bare imports like
  // `react/jsx-runtime`.
  void externals;
  const externalNames: string[] = [];

  const buildOptions: BuildOptions = {
    entryPoints: [args.entryPath],
    bundle: true,
    format: "esm",
    platform: "browser",
    target: "es2020",
    minify: true,
    sourcemap: false,
    external: externalNames,
    plugins: esbuildPlugins,
    write: false,
    legalComments: "none",
    banner: {
      js: `/* simularca-plugin-bundle sharedThree=${String(!inlineExternals && Boolean(threeExportsMap))} versions=${JSON.stringify(externals)} */`
    }
  };

  const result = await build(buildOptions);
  const outputs: OutputFile[] = result.outputFiles ?? [];
  // With `write: false` and no `outdir`, esbuild names the output `<stdout>`
  // (a literal string, not a file extension). Filter by content type
  // instead: prefer files whose path ends in `.js`, but fall back to the
  // sole output when there's exactly one.
  let jsOutputs = outputs.filter((file) => file.path.endsWith(".js"));
  if (jsOutputs.length === 0 && outputs.length === 1) {
    jsOutputs = outputs;
  }
  if (jsOutputs.length === 0) {
    throw new Error(
      `esbuild produced no usable JS output (paths: ${outputs.map((f) => f.path).join(", ") || "(none)"}).`
    );
  }
  if (jsOutputs.length > 1) {
    throw new Error(
      `esbuild produced multiple JS outputs (${String(jsOutputs.length)}); plugin bundles must be a single file.`
    );
  }
  const first = jsOutputs[0];
  if (!first) {
    throw new Error("esbuild output array unexpectedly empty.");
  }
  const bytes = first.contents;
  const sha256 = createHash("sha256").update(bytes).digest("hex");
  return {
    bytes,
    sha256,
    externals,
    byteSize: bytes.byteLength
  };
}

/** Resolve the plugin's main entry from its package.json. */
export function resolvePluginEntry(pluginRoot: string): string {
  const pkgPath = path.join(pluginRoot, "package.json");
  if (!fs.existsSync(pkgPath)) {
    throw new Error(`Plugin missing package.json: ${pluginRoot}`);
  }
  const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8")) as { main?: string };
  if (!pkg.main) {
    throw new Error(`Plugin package.json has no "main": ${pluginRoot}`);
  }
  return path.join(pluginRoot, pkg.main);
}
