import type { ActorNode, SceneState } from "@/core/types";

/**
 * Remove generated Array-instance actors from an actor map + scene root, also
 * pruning them from every parent's `childActorIds` and from `scene.actorIds`.
 *
 * Generated actors are derived from an Array actor's authored template and are
 * regenerated by the `ArrayReconciler`, so they must never be written to project
 * snapshots or undo history. Returns shallow copies; callers deep-clone as
 * needed.
 */
export function stripGeneratedActors(
  actors: Record<string, ActorNode>,
  scene: SceneState
): { actors: Record<string, ActorNode>; scene: SceneState } {
  const outActors: Record<string, ActorNode> = {};
  for (const [id, actor] of Object.entries(actors)) {
    if (actor.generatedByActorId) {
      continue;
    }
    outActors[id] = {
      ...actor,
      childActorIds: actor.childActorIds.filter(
        (childId) => actors[childId] && !actors[childId]!.generatedByActorId
      )
    };
  }
  const outScene: SceneState = {
    ...scene,
    actorIds: scene.actorIds.filter((id) => actors[id] && !actors[id]!.generatedByActorId)
  };
  return { actors: outActors, scene: outScene };
}
